# Generated by Django 3.2.6 on 2021-08-25 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phoneNumber', models.IntegerField()),
                ('transactor', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
